edition = "2021"
# error_on_line_overflow = true
# error_on_unformatted = true
max_width = 80
newline_style = "Unix"
tab_spaces = 2
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
